version: '3'

services:

  app: 
    build: .
    container_name: atendemais-backend-api
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    image: mariadb
    container_name: antedemais-db
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - atendemais-volume-dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=atendemais
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
volumes:
 atendemais-volume-dbdata:
  external: true 

