version: '3'

services:

  app: 
    build: .
    container_name: your-app-name
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    image: mariadb
    container_name: your-container-name-db
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - your-volume-any-name:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=atendemais
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
volumes:
 your-volume-any-name:
  external: true 

